Repository nestsolutionsllc/nest-hr, pull requests merged in 2022-07, with the labels that each got.

#25 feat: Front-end eslint error fixed
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Loader.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/index.ts
  frontend/src/layouts/MainLayout.tsx
  frontend/src/layouts/index.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/signIn.tsx
  frontend/src/providers/AlertProvider.tsx
  frontend/src/providers/AuthProvider.tsx
  frontend/src/providers/index.ts
  frontend/src/theme/theme.ts
  package-lock.json
Labels: bug

#24 docs: add readme in frontend
  frontend/README.md
Labels: documentation

#26 feat: configure workpace settings
  .prettierrc
  .vscode/settings.json
Labels: enhancement
